### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [ ]:
import numpy as np

# Matrice survey
survey_matrix = np.array([[25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13]])

# 1. Seleziona solo gli intervistati con almeno 12 anni di istruzione
filtro = survey_matrix[:, 2] >= 12
intervistati_istr = survey_matrix[filtro]
print("Intervistati con almeno 12 anni di istruzione:\n", intervistati_istr)

# 2. In un'unica riga: seleziona i redditi degli intervistati con almeno 12 anni di istruzione
redditi_istr = survey_matrix[survey_matrix[:, 2] >= 12, 1]
print("\nRedditi corrispondenti:\n", redditi_istr)

# 3. In un'unica riga: calcola il reddito medio degli intervistati con almeno 12 anni di istruzione
reddito_medio = np.mean(survey_matrix[survey_matrix[:, 2] >= 12, 1])
print("\nReddito medio:\n", round(reddito_medio, 2))


Intervistati con almeno 12 anni di istruzione:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]

Redditi corrispondenti:
 [52000 63000 58000]

Reddito medio:
 57666.67
