### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [7]:
import numpy as np

a = np.random.rand(10,3)
print("Array a:\n", a)

col = np.abs(a - 0.5).argmin(axis=1)
righe = np.arange(10)
b = a[righe, col]
print("\nValori più vicini a 0.5:\n", b)

Array a:
 [[0.33603644 0.06174883 0.77688098]
 [0.99076581 0.01195246 0.68402474]
 [0.7246036  0.27260688 0.30946505]
 [0.5048304  0.85899783 0.61646766]
 [0.44967359 0.47604826 0.20755121]
 [0.17181681 0.51672702 0.1702402 ]
 [0.34444909 0.21427584 0.3573681 ]
 [0.79602556 0.8365109  0.15488868]
 [0.62037802 0.40363195 0.13936272]
 [0.69241026 0.34899471 0.55261802]]

Valori più vicini a 0.5:
 [0.33603644 0.68402474 0.30946505 0.5048304  0.47604826 0.51672702
 0.3573681  0.79602556 0.40363195 0.55261802]
